### ISSUE TITLE
 ESP32c3 with FT6206 in Arduino to use this library but no response

### ISSUE THREAD

**Issue by Javison666** [DustinWatts/FocalTech_Touch#3]
Do I need to make additional settings? I used ESP32c3 in Arduino to use this library, but there was no response

**Comment by DustinWatts** [comment]
Hi @Javison666 Did you try the example code? And if so, what happens?

Also, did you change SDA and SCL to the correct SDA and SCL pins for the ESP32c3? you can use `//begin(40, SDA, SCL)` instead of `ts.begin40)` to set custom pins.

Also it helps if you can post the output of the serial monitor here so we can have a look.

**Comment by Javison666** [comment]
> Hi @Javison666 Did you try the example code? And if so, what happens?
> 
> Also, did you change SDA and SCL to the correct SDA and SCL pins for the ESP32c3? you can use `//begin(40, SDA, SCL)` instead of `ts.begin40)` to set custom pins.
> 
> Also it helps if you can post the output of the serial monitor here so we can have a look.


It's not a problem with the code repository. I tested and found that the pin comments provided by the module were incorrect, finally.It's not very reliable to find it from the second-hand market😄.

**Comment by DustinWatts** [comment]
Well. At least we can close this as completed 😄
